server:
  port: 8080

database:
  host: localhost
  port: 5432
  user: tms
  password: tms123
  dbname: tmsdb
  sslmode: disable

redis:
  host: localhost
  port: 6379

jwt:
  secret: "localsecret"
  expire_minutes: 60

log:
  logLevel: debug
  fileLogName: "./storages/logs/dev.log"
  maxSize:    500
  maxBackups: 3
  maxAge:     28
  compress:   true